@startuml
rectangle "* common Components *" {
[Authorization service] #White
[Audit & logging ] #White
[Authentication service] #White
[User self-service] #White
[Administration service] #White
}
newpage
package "Authentication Service" {
[IDIR] --> LINK
[MoH LDAP] --> LINK
[PHSA] --> LINK
[BCEID] --> LINK
[BCSC(future)] --> LINK
}
package "Audit & Logging" {
[ Record events ] --> view
}
package "user self-service" {
LINK --> [ID linking]
 [view application role]
}

package "Administration service" {
[View user]
[Query clients]
[Manage users]
[Manage clients]
view --> [View events]
[identity provider configuration]
}
newpage
package "Authorization Service" {
[RBAC - users accessing BC health web application]
[RBAC - client application access to BC Health resources behind the BC Health API gateway]
}
@enduml
