@startuml OIDC_grant_flow
autonumber

    actor "User  \n(browser / user-agent)"

   "User  \n(browser / user-agent)" -> "client application\n (relying party)" : (assumption) user is authenticated

   "User  \n(browser / user-agent)" -> "client application\n (relying party)" :  user access protected resources from provider API

    "client application\n (relying party)" -> "BC Health OIDC service \n (keycloak OIDC service)" : Authorization request

      "User  \n(browser / user-agent)" -> "BC Health OIDC service \n (keycloak OIDC service)" : User provide consent ( if enabled)

    "BC Health OIDC service \n (keycloak OIDC service)" -> "client application\n (relying party)" : Access Token

    "client application\n (relying party)" -> "BC Health API Gateway" : API provider request (access token)

    "BC Health API Gateway"  -> "BC Health API Gateway"  : validate token and check authorization

    "BC Health API Gateway"  -> "provider API \n ( backend API)" : forward request (access token)

   "provider API \n ( backend API)" <->  "BC Health OIDC service \n (keycloak OIDC service)"  :  (if needed) request userinfo (access token)

   "provider API \n ( backend API)" -> "provider API \n ( backend API)"   :  process request

   "provider API \n ( backend API)" ->  "BC Health API Gateway"  :  API provider response

    "BC Health API Gateway" -> "client application\n (relying party)" : API provider Response

    "client application\n (relying party)" -> "User  \n(browser / user-agent)"    : Application Response

@enduml